# Generated by Django 4.2.7 on 2026-03-31 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('cost_centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحل'), ('cancelled', 'ملغي')], default='draft', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('is_posted', models.BooleanField(default=False)),
                ('unposted_at', models.DateTimeField(blank=True, null=True)),
                ('is_adjustment', models.BooleanField(default=False, help_text='هل هذا القيد تسوية جردية؟')),
                ('adjustment_type', models.CharField(choices=[('none', 'لا يوجد'), ('inventory', 'جرد مخزون'), ('bank', 'تسوية بنكية'), ('depreciation', 'إهلاك'), ('currency', 'فروق عملة'), ('accrual', 'مصروفات مستحقة'), ('prepaid', 'مصروفات مدفوعة مقدماً')], default='none', help_text='نوع التسوية الجردية', max_length=20)),
                ('adjustment_reference', models.CharField(blank=True, help_text='رقم المستند المرجعي (محضر جرد، كشف بنك، إلخ)', max_length=100)),
                ('adjustment_notes', models.TextField(blank=True, help_text='ملاحظات إضافية عن التسوية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_entries', to=settings.AUTH_USER_MODEL)),
                ('unposted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unposted_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount_foreign', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('cash_flow_category', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='cost_centers.costcenter')),
                ('cost_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='cost_centers.costelement')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='currencies.currency')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='journal.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('period', models.PositiveSmallIntegerField()),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'ordering': ['account', 'fiscal_year', 'period'],
                'unique_together': {('account', 'fiscal_year', 'period')},
            },
        ),
    ]
