# Generated by Django 4.2.7 on 2026-03-31 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name_ar', models.CharField(max_length=50)),
                ('name_en', models.CharField(blank=True, max_length=50)),
                ('symbol', models.CharField(blank=True, max_length=5)),
                ('is_base', models.BooleanField(default=False)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=18)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('date', models.DateField()),
                ('source', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='currencies.currency')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
