# Generated by Django 4.2.7 on 2026-03-31 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
        ('cost_centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costallocationrun',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.journalentry'),
        ),
        migrations.AddField(
            model_name='costallocationrun',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='cost_centers.costallocationrule'),
        ),
    ]
